"""
safety_rules.py — Phase 7 requirement: URGENT risk is decided by an
explicit, human-curated rule engine — NEVER by the ML model's output.

This module is intentionally simple and auditable: a fixed list of
red-flag symptoms/combinations that, if present, force risk_level to
"URGENT" regardless of what the ML model predicts. It also carries the
"what to monitor" / "when to seek help" knowledge base (Phase 8), which
is likewise rule-based rather than generated by an LLM, per the
project's safety requirements.
"""
from __future__ import annotations

from typing import Dict, List

# Symptoms that, individually, always trigger URGENT.
# Kept deliberately conservative/broad for an educational project —
# false positives (over-triggering urgent) are the safer failure mode
# than false negatives here.
RED_FLAG_SYMPTOMS = {
    "chest_pain",
    "breathlessness",
    "coma",
    "acute_liver_failure",
    "stomach_bleeding",
    "bloody_stool",
    "weakness_of_one_body_side",
    "slurred_speech",
    "altered_sensorium",
    "fast_heart_rate",
}

# Combinations that are urgent together even if no single symptom above
# fires alone (each inner list = a symptom set; ANY full match triggers URGENT).
RED_FLAG_COMBINATIONS: List[set] = [
    {"high_fever", "stiff_neck"},                 # possible meningitis pattern
    {"high_fever", "breathlessness"},
    {"high_fever", "yellowing_of_eyes"},           # possible severe hepatic involvement
    {"vomiting", "blood_in_sputum"},
]


def check_red_flags(symptoms: List[str]) -> Dict:
    """
    Returns {"is_urgent": bool, "triggered_by": [...]} — triggered_by
    lists the specific symptom(s)/combination(s) that fired, for
    transparency in the UI (never invent a reason that wasn't actually
    matched).
    """
    symptom_set = set(symptoms)
    triggered: List[str] = []

    single_hits = symptom_set & RED_FLAG_SYMPTOMS
    triggered.extend(sorted(single_hits))

    for combo in RED_FLAG_COMBINATIONS:
        if combo.issubset(symptom_set):
            triggered.append(" + ".join(sorted(combo)))

    return {"is_urgent": len(triggered) > 0, "triggered_by": triggered}


# ---------------------------------------------------------------------------
# "What to monitor" / "When to seek professional help" knowledge base.
# Deliberately generic and non-diagnostic — the same guidance structure
# applies across risk categories, with wording that escalates in urgency.
# This is NOT meant to vary by disease label; it's meant to give safe,
# consistent, informational guidance regardless of which condition the
# model estimated.
# ---------------------------------------------------------------------------

PROGRESSION_GUIDANCE = {
    "LOW": {
        "what_to_monitor": [
            "Whether symptoms persist beyond a few days",
            "Whether new symptoms appear",
            "Whether symptoms interfere with daily activities",
        ],
        "when_to_seek_help": [
            "Symptoms last longer than a week",
            "Symptoms worsen instead of improving",
            "Any new or unusual symptom develops",
        ],
    },
    "MODERATE": {
        "what_to_monitor": [
            "Whether symptoms become more severe",
            "Whether new symptoms appear",
            "Whether symptoms persist despite rest and hydration",
        ],
        "when_to_seek_help": [
            "Symptoms worsen",
            "Symptoms persist beyond a few days",
            "Fever remains high or returns after improving",
            "Severe or concerning symptoms occur",
        ],
    },
    "HIGH": {
        "what_to_monitor": [
            "Whether symptoms are rapidly worsening",
            "Whether any red-flag symptom (e.g. breathing difficulty, chest pain) appears",
            "Overall hydration, alertness, and ability to function normally",
        ],
        "when_to_seek_help": [
            "Consider a medical consultation soon rather than waiting",
            "Any worsening of breathing, consciousness, or pain",
            "Symptoms significantly affecting eating, drinking, or basic activity",
        ],
    },
    "URGENT": {
        "what_to_monitor": [
            "This category is not for self-monitoring at home",
        ],
        "when_to_seek_help": [
            "Seek urgent professional medical evaluation now",
            "Do not wait to see if symptoms improve on their own",
        ],
    },
}


def get_progression_guidance(risk_level: str) -> Dict:
    return PROGRESSION_GUIDANCE.get(risk_level, PROGRESSION_GUIDANCE["MODERATE"])
